name: repo_DEP-2_RTD-1-test
channels: 
  - defaults
dependencies:
    # Base depends
  - python
  - pip

    # MDAnalysis
  - cython
  - numpy
  - MDAnalysis

    # Testing
  - pytest
  - pytest-cov
  - pytest-xdist

  # Pip-only installs
  - pip:
    - codecov

