name: Pip build from source
on:
  workflow_call:

jobs:
  install_from_source_pip:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python {{ '${{ matrix.python-version }}' }}
      uses: actions/setup-python@v3
      with:
        python-version: {{ '${{ matrix.python-version }}' }}

    - name: Build from source
      run: |
        python --version
        pip install -e ".[test,doc]"

    - name: Check success
      run: |
        python -c "import MDAnalysis as mda; print(f'MDAnalysis version:', mda.__version__)"
        python -c "import {{cookiecutter.package_name}}; print('{{cookiecutter.package_name}} version:', {{cookiecutter.package_name}}.__version__)"
