name: GH Actions CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: {{ '${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}' }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  main_tests:
    if: "github.repository == '{{ cookiecutter.github_url }}'"
    uses: ./.github/workflows/subflows/main_tests.yaml
  pylint:
    if: "github.repository == '{{ cookiecutter.github_url }}'"
    uses: ./.github/workflows/subflows/pylint.yaml
  pypi:
    if: "github.repository == '{{ cookiecutter.github_url }}'"
    uses: ./.github/workflows/subflows/pypi.yaml
  build_from_source_pip:
    if: "github.repository == '{{ cookiecutter.github_url }}'"
    uses: ./.github/workflows/subflows/build_from_source_pip.yaml
{% if cookiecutter.dependency_source != 'Dependencies from pip only (no conda)' %}
  build_from_source_conda:
    if: "github.repository == '{{ cookiecutter.github_url }}'"
    uses: ./.github/workflows/subflows/build_from_source_conda.yaml
{% endif %}
  