name: GH Actions CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  main_tests:
    if: "github.repository == 'cookie/repo_DEP-3_RTD-2'"
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [macOS-latest, ubuntu-latest, windows-latest]
          python-version: ["3.8", "3.9", "3.10"]
    env:
      CYTHON_TRACE_NOGIL: 1
      MPLBACKEND: agg

    steps:
    - uses: actions/checkout@v3

    - name: Set up OS
      uses: ./.github/actions/setup-os
      with:
        os-type: ${{ matrix.os }}

    - name: Build information
      run: |
        echo "OS: ${OS_NAME}"
        uname -a
        df -h
        ulimit -a
        ${CC} -v
        ${CXX} -v
        ${FC} -v
        echo "numprocs=${numprocs}"


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install testing dependencies
      shell: bash
      run: |
        python -m pip install -U pytest pytest-xdist pytest-cov codecov



      - name: Install package
      run: |
        python -m pip install .


    - name: Python information
      run: |
        which python
        which pip
        pip list


    - name: Run tests
      run: |
        pytest -n $numprocs -v --cov=repo_DEP-3_RTD-2 --cov-report=xml --color=yes repo_DEP-3_RTD-2/tests/

    - name: codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.xml
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        verbose: True


  pylint_check:
    if: "github.repository == 'cookie/repo_DEP-3_RTD-2'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Pylint
      run: |
        which pip
        which python
        pip install pylint

    - name: Run Pylint
      env:
        PYLINTRC: .pylintrc
      run: |
        pylint repo_DEP-3_RTD-2


  pypi_check:
    if: "github.repository == 'cookie/repo_DEP-3_RTD-2'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}



    - name: Install dependencies
      run: |
        pip install setuptools cython numpy twine

    - name: Build package
      run: |
        python setup.py sdist

    - name: Check package build
      run: |
        DISTRIBUTION=$(ls -t1 package/dist/repo_DEP-3_RTD-2-*.tar.gz | head -n 1)
        test -n "${DISTRIBUTION}" || { echo "no distribution package/dist/repo_DEP-3_RTD-2-*.tar.gz found"; exit 1; }
        echo "twine check $DISTRIBUTION"
        twine check $DISTRIBUTION
